### ISSUE TITLE
Design Event Page In Figma - 1

### ISSUE THREAD

**Issue by abhayguptas** [techbastic/techbastic#1]
## 1. Design the Event Page

- **Objective**: Create a page that matches the current theme of the project ( [TechBastic Website ](https://www.techbastic.co/)) 
- **Sections**:
  - **Header**: Title "Events" with filters for "Online" and "Offline."
  - **Event Listing**: List online and offline events in two separate sections.
    - Each event should have:
      - Event name
      - Date and time
      - Location (if offline) or link (if online)
      - Short description
    - **Dynamic routing**: Clicking an event leads to a detailed event page.
  - **Event Details** (Dynamic routing):
    - Event description
    - Speakers or key people involved
    - Venue details (for offline events)
    - Registration link
    - **Reviews section**: Allow users to leave and view reviews for each event.

### Important 

-  This is the only designing part. You have to create a visual design in figma that matches the theme of our current [website](https://www.techbastic.co/).

- We are going to make 2 people work on this issue at a same time and merge the PR of 1 who's design is better. For fair juding we'll do a voting. From the two designs, the one who receive highest votes will win. 

Thanks, Happy Hacktober  🎃

**Comment by atraxia24** [comment]
I'd like to work on this design. Just to make sure this is only the designing part right?

**Comment by abhayguptas** [comment]
> I'd like to work on this design. Just to make sure this is only the designing part right?

Yes, this is just to create the design for the page. Have you joined our community?

**Comment by atraxia24** [comment]
> > I'd like to work on this design. Just to make sure this is only the designing part right?
> 
> Yes, this is just to create the design for the page. Have you joined our community?

 Great! Can you assign this to me and yeah I have joined the community

**Comment by abhayguptas** [comment]
LG ✨ @Muskan2404!

- Make sure you read the description carefully and also the [contributing guidlines](https://github.com/techbastic/techbastic/blob/main/CONTRIBUTING.md)
- Please give me the access to the design as you create and also take feedback as you make progress. 
- You can connect with me in the group itself. 

Excited to see the design!

Happy Hacktober from Team TechBastic 💫

**Comment by Muskan2404** [comment]
> LG ✨ @Muskan2404!
> 
> * Make sure you read the description carefully and also the [contributing guidlines](https://github.com/techbastic/techbastic/blob/main/CONTRIBUTING.md)
> * Please give me the access to the design as you create and also take feedback as you make progress.
> * You can connect with me in the group itself.
> 
> Excited to see the design!
> 
> Happy Hacktober from Team TechBastic 💫

Sure. Do I share the figma link with you personally or in the group? Either way please give me your discord id and the channel name where I should ask for feedback

**Comment by professorabhay** [comment]
@abhayporwals

**Comment by adisuyash** [comment]
> > LG ✨ @Muskan2404!
> > 
> > * Make sure you read the description carefully and also the [contributing guidlines](https://github.com/techbastic/techbastic/blob/main/CONTRIBUTING.md)
> > * Please give me the access to the design as you create and also take feedback as you make progress.
> > * You can connect with me in the group itself.
> > 
> > Excited to see the design!
> > Happy Hacktober from Team TechBastic 💫
> 
> Sure. Do I share the figma link with you personally or in the group? Either way please give me your discord id and the channel name where I should ask for feedback

Hi @Muskan2404, please share access to the Figma file using this email address **techbastic@gmail.com**. Thanks!

**Comment by Muskan2404** [comment]
> > > LG ✨ @Muskan2404!
> > > 
> > > * Make sure you read the description carefully and also the [contributing guidlines](https://github.com/techbastic/techbastic/blob/main/CONTRIBUTING.md)
> > > * Please give me the access to the design as you create and also take feedback as you make progress.
> > > * You can connect with me in the group itself.
> > > 
> > > Excited to see the design!
> > > Happy Hacktober from Team TechBastic 💫
> > 
> > 
> > Sure. Do I share the figma link with you personally or in the group? Either way please give me your discord id and the channel name where I should ask for feedback
> 
> Hi @Muskan2404, please share access to the Figma file using this email address **[techbastic@gmail.com](mailto:techbastic@gmail.com)**. Thanks!

https://www.figma.com/design/TeOGumCcJ5T1GYRvPo0wIB/TechBastic?node-id=0-1&t=JtBIkis0Ue2GAK6Z-1

**Comment by atraxia24** [comment]
> > > LG ✨ @Muskan2404!
> > > 
> > > * Make sure you read the description carefully and also the [contributing guidlines](https://github.com/techbastic/techbastic/blob/main/CONTRIBUTING.md)
> > > * Please give me the access to the design as you create and also take feedback as you make progress.
> > > * You can connect with me in the group itself.
> > > 
> > > Excited to see the design!
> > > Happy Hacktober from Team TechBastic 💫
> > 
> > 
> > Sure. Do I share the figma link with you personally or in the group? Either way please give me your discord id and the channel name where I should ask for feedback
> 
> Hi @Muskan2404, please share access to the Figma file using this email address **[techbastic@gmail.com](mailto:techbastic@gmail.com)**. Thanks!

Please check if you're okay with the current design. Don't worry about the colours I'll adjust it once the design is finalised.

**Comment by abhayguptas** [comment]
I checked the design, and it looks good! However:

- The sidebar in the design doesn't match the current theme. We have a navbar at the top. Please take a look at the website.
- Include 'Past Events' as a heading or section if possible.
- Also, add a section with reference images of social media posts and feedback from attendees."

![image](https://github.com/user-attachments/assets/64847aae-a57b-4f9d-b4b0-9db79bd1bde7)


- We are going to add the event section just after the project.

**Comment by atraxia24** [comment]
> I checked the design, and it looks good! However:
> 
> * The sidebar in the design doesn't match the current theme. We have a navbar at the top. Please take a look at the website.
> * Include 'Past Events' as a heading or section if possible.
> * Also, add a section with reference images of social media posts and feedback from attendees."
> 
> * We are going to add the event section just after the project.

 I'm left with the section where people can give feedback but the rest is done. Please check again and tell if there's seomething to be changed.

**Comment by abhayguptas** [comment]
looks good!
one more addon - make a section below it saying "what our attendees says" where all the feedbacks, posts will shown.

**Comment by atraxia24** [comment]
> looks good! one more addon - make a section below it saying "what our attendees says" where all the feedbacks, posts will shown.

There isn't any space below to make another section. How about I design another page for it so when the user clicks on the give feedback button it redirects them to that page?

**Comment by adisuyash** [comment]
Hi @Muskan2404,
If there's any issue regarding what you need to include in the landing pages, refer to https://x.com/techbastic
Although right now, there's no official Figma file for our website, we need to create it too...
After that, this issue could be easily resolved.

Let me know if you can design a General Homepage for Tech Bastic using some references from websites like:
1. https://eddiehub.org/
2. https://updraft.cyfrin.io/
3. https://www.hackquest.io/
4. https://www.4c.rocks/

I'll give you an invite to Tech Bastic's Official Figma workspace if you're up to that. Thanks

**Comment by atraxia24** [comment]
> Hi @Muskan2404, If there's any issue regarding what you need to include in the landing pages, refer to https://x.com/techbastic Although right now, there's no official Figma file for our website, we need to create it too... After that, this issue could be easily resolved.
> 
> Let me know if you can design a General Homepage for Tech Bastic using some references from websites like:
> 
> 1. https://eddiehub.org/
> 2. https://updraft.cyfrin.io/
> 3. https://www.hackquest.io/
> 4. https://www.4c.rocks/
> 
> I'll give you an invite to Tech Bastic's Official Figma workspace if you're up to that. Thanks

I need to clear up a few things regarding this. Can I email you?

**Comment by adisuyash** [comment]
Obv you can email me anytime but let's hop on Discord: https://discord.com/invite/MSRnjkHcxK
so you get things clear

**Comment by adisuyash** [comment]
@Muskan2404 feel free to use the #general channel in Discord for further communications

**Comment by atraxia24** [comment]
> @Muskan2404 feel free to use the #general channel in Discord for further communications

Sure. However it would be great if you could reply a bit faster there. Thanks!
